Refactor/add spearman ground truth for scoring
tensorplex-labs/dojo pull request #37
Opened 2024-09-13 05:00 UTC by codebender37

2024-09-16 09:04 UTC, jarvis8x7b requested changes

2024-09-16 17:51 UTC, codebender37 commented on template/protocol.py
> +    )
I am not sure what you mean here, I thought ` default_factory=dict,` would create empty object by default in every instance

2024-09-18 03:25 UTC, jarvis8x7b commented on template/protocol.py
> +    )
my bad i missed this

2024-09-18 08:58 UTC, jarvis8x7b approved these changes
lgtm

2024-09-18 09:01 UTC, merged